"""add document ingestion fields

Revision ID: 68546edeb47b
Revises: 6d97f1926f62
Create Date: 2026-09-24 15:47:52.120709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '68546edeb47b'
down_revision: Union[str, Sequence[str], None] = '6d97f1926f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    document_status = postgresql.ENUM(
        "pending",
        "processing",
        "ready",
        "failed",
        name="document_status",
        create_type=False,
    )

    document_status.create(
        op.get_bind(),
        checkfirst=True,
    )

    op.add_column('documents', sa.Column('filename', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('content_type', sa.String(length=100), nullable=False))
    op.add_column('documents', sa.Column('status', document_status, nullable=False))
    op.add_column('documents', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('documents', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('documents', 'created_at')
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'content_type')
    op.drop_column('documents', 'filename')

    postgresql.ENUM(
        name="document_status",
        create_type=False,
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###
