"""add embedding to document chunks

Revision ID: d3a3866a94da
Revises: 9c03dd11194e
Create Date: 2026-10-01 16:31:23.432846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'd3a3866a94da'
down_revision: Union[str, Sequence[str], None] = '9c03dd11194e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_chunks",
        sa.Column(
            "embedding",
            Vector(1536),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        'document_chunks',
        'embedding'
    )
    # ### end Alembic commands ###
